# Autostart
go.server.autoStart=true
go.server.port=9999
go.server.boardSize=19

# DB in a file
spring.datasource.url=jdbc:h2:file:./data/godb

# Do not delete data
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
